categorieproduit_index:
    path:     /
    defaults: { _controller: "GestionProduitBundle:CategorieProduit:index" }
    methods:  GET

categorieproduit_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProduitBundle:CategorieProduit:show" }
    methods:  GET

categorieproduit_new:
    path:     /new
    defaults: { _controller: "GestionProduitBundle:CategorieProduit:new" }
    methods:  [GET, POST]

categorieproduit_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProduitBundle:CategorieProduit:edit" }
    methods:  [GET, POST]

categorieproduit_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProduitBundle:CategorieProduit:delete" }
    methods:  DELETE
