produit_index:
    path:     /
    defaults: { _controller: "GestionProduitBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProduitBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /new
    defaults: { _controller: "GestionProduitBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProduitBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProduitBundle:Produit:delete" }
    methods:  DELETE
produit_shop:
    path:     /shop
    defaults: { _controller: "GestionProduitBundle:Produit:shop" }


produit_cat:
    path:     /{id}/shop
    defaults: { _controller: "GestionProduitBundle:Produit:categories" }
    methods:  GET

produit_details:
    path:      /{id}/details
    defaults: { _controller: "GestionProduitBundle:Produit:details" }

    methods:  [GET, POST]
produit_listp:
    path:     /listp
    defaults: { _controller: "GestionProduitBundle:Produit:listp" }

produit_comment:
    path:      /comment
    defaults: { _controller: "GestionProduitBundle:Produit:comment" }

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

produit_deleteC:
    path:      /deleteC/{id}
    defaults: { _controller: "GestionProduitBundle:Produit:deleteC" }
    methods:  [GET, POST]

produit_noter:
    path:      /noter/{id}/{note}
    defaults: { _controller: "GestionProduitBundle:Produit:noter" }

