produit_index:
    path:     /
    defaults: { _controller: "GestionProduitBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /{id}/show
    defaults: { _controller: "GestionProduitBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /new
    defaults: { _controller: "GestionProduitBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionProduitBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionProduitBundle:Produit:delete" }
    methods:  DELETE
produit_shop:
    path:     /shop
    defaults: { _controller: "GestionProduitBundle:Produit:shop" }


produit_cat:
    path:     /{id}/shop
    defaults: { _controller: "GestionProduitBundle:Produit:categories" }
    methods:  GET

produit_details:
    path:      /{id}/details
    defaults: { _controller: "GestionProduitBundle:Produit:details" }
    methods:  GET
