produit_index:
    path:     /admin/produit
    defaults: { _controller: "GestionProduitBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /admin/produit/{id}/show
    defaults: { _controller: "GestionProduitBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /admin/produit/new
    defaults: { _controller: "GestionProduitBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /admin/admin/produit/{id}/edit
    defaults: { _controller: "GestionProduitBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /admin/produit/{id}/delete
    defaults: { _controller: "GestionProduitBundle:Produit:delete" }
    methods:  DELETE
produit_shop:
    path:     /produit/shop
    defaults: { _controller: "GestionProduitBundle:Produit:shop" }


produit_cat:
    path:     /produit/{id}/shop
    defaults: { _controller: "GestionProduitBundle:Produit:categories" }
    methods:  GET

produit_details:
    path:      /produit/{id}/details
    defaults: { _controller: "GestionProduitBundle:Produit:details" }

    methods:  [GET, POST]
produit_listp:
    path:     /admin/listp
    defaults: { _controller: "GestionProduitBundle:Produit:listp" }

produit_comment:
    path:      /produit/comment
    defaults: { _controller: "GestionProduitBundle:Produit:comment" }

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

produit_deleteC:
    path:      /produit/deleteC/{id}
    defaults: { _controller: "GestionProduitBundle:Produit:deleteC" }
    methods:  [GET, POST]

produit_noter:
    path:      /produit/noter/{id}/{note}
    defaults: { _controller: "GestionProduitBundle:Produit:noter" }

