fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
#/routing.yml or /all.xml
app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Default:indexAdmin }
