user_amis:
    resource: "@UserBundle/Controller/amisController.php"
    type:     annotation

user_commentaire:
    resource: "@UserBundle/Controller/commentaireController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /

gestion_produit:
    resource: "@GestionProduitBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

publication:
    resource: "@UserBundle/controller"
    prefix:   /

index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Default:indexAdmin }

notifications_admin:
    path:     /notifs
    defaults: { _controller: AppBundle:Default:notifiactionsAdmin }
