app:
    resource: '@AppBundle/Controller/'
    type: annotation

gestion_produit:
    resource: "@GestionProduitBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

admin:
    path:     /admin
    defaults: { _controller: AppBundle:Default:indexAdmin }
